### ISSUE TITLE
Table trait -> "value" can store only number 

### ISSUE THREAD

**Issue by gabrielbouleau** [mangal-interactions/mangal-api#17]
In the Kolpelke dataset, the traits are type of parasitisms (character) and not mesurements (interger).

`        value: {
            type: DataTypes.FLOAT,
            allowNull: false,
            comment: "Value of the trait/attribute"`

Is there a type of attribute that can store both numbers and characters?

**Comment by tpoisot** [comment]
I think it should be a type of interactions, not a trait

Sent from BlueMail<http://www.bluemail.me/r?b=12687>
On Apr 10, 2018, at 11:30, Gabriel Bergeron <notifications@github.com<mailto:notifications@github.com>> wrote:

In the Kolpelke dataset, the traits are type of parasitisms (character) and not mesurements (interger).

value: { type: DataTypes.FLOAT, allowNull: false, comment: "Value of the trait/attribute"

Is there a type of attribute that can store both numbers and characters?
