### ISSUE TITLE
Missing interaction direction

### ISSUE THREAD

**Issue by clementviolet** [mangal-interactions/mangal-api#32]
In at least the network #1227, the direction of the interactions seems not to be detected by the API, but are documented in the DB. See the picture below :
![mangal_api_bug](https://user-images.githubusercontent.com/22980442/53701621-3b28df80-3dff-11e9-88ca-982558c7629d.png)

**Comment by SteveViss** [comment]
@clementviolet , is it solved?

**Comment by clementviolet** [comment]
Yup !
