### ISSUE TITLE
Attribute duplicate

### ISSUE THREAD

**Issue by gabrielbouleau** [mangal-interactions/mangal-api#36]
Il y a des duplicat dans la table attribut depuis la modification `tolower` pour les entrés dans les tables.

Besoin d'un UPDATE pour fusionner les entrés qui sont des doublons

**Comment by BenMerSci** [comment]
Delete the Attribute with attribute_id = 35
Change all interactions with attribute_id = 2 to attribute_id = 36 (and then delete the Attribute with attribute_id =2)
Change all interactions with attribute_id = 17 to attribute_id = 38 (and then delete the Attribute with attribute_id =17)

**Comment by SteveViss** [comment]
Solved with SQL instructions.
