### ISSUE TITLE
Prepopulate standard metrics

### ISSUE THREAD

**Issue by SteveViss** [mangal-interactions/mangal-api#51]
> For the network datatable, this would include # of nodes and interactions, potentially a modularity factor, and the interactions database with degree and eigen.centrality.

Recommendation from https://github.com/ropensci/software-review/issues/332 (by @arw36)

**Comment by tpoisot** [comment]
I don't agree with this. Not very useful, let's not add it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SteveViss** [comment]
It might be useful to filter networks based on properties but it's a lot of work for few functionalities. Each properties have to be set as generated columns (see https://www.postgresql.org/docs/12/ddl-generated-columns.html). I close it for the moment.
